- id: private-calls-check
  name: private-calls-check
  description: Checks whether a private function is being called outside of where it should be.
  entry: private-calls-check
  language: python
  types: [python]